name: Build .NET Framework App

on:
  push: 
     branches: [ "master" ]

     jobs:
      build:
       runs-on: windows-latest

       steps:
        - uses: actions/checkout@v4

        - uses: microsoft/setup-msbuild@v2
        - uses: NuGet/setup-nuget@v2

        - name:  Build
        run: msbuild "POE_part1.csproj" /p:Configuration=Release
